name: UralClans2
main: ru.jampire.bukkit.uralclans2.Main
author: Jampire (Appended Ilya_Evtukhov)
version: 2.2.5f
depend: [WorldGuard, WorldEdit]
commands:
    clan:
        aliases: [c]
permissions:
    UralClans2.warm.ignore:
        default: op
    UralClans2.use:
        default: op
    UralClans2.admin:
        default: op
    UralClans2.moder:
        default: op
    UralClans2.leader:
        default: op